Repository chainguard-dev/image-comparison, pull requests merged in 2022-11, with the labels that each got.

#13 Add gitsign policies
  .chainguard/source.yaml
Labels: enhancement

#10 Create bandit.yml
  .github/workflows/bandit.yml
Labels: enhancement

#8 Create black.yml
  .github/workflows/black.yml
Labels: enhancement

#6 Add Pylint to CI
  .github/workflows/pylint.yml
Labels: enhancement

#11 Add Filtering Script
  .gitignore
  filter_data.py
  main.py
  test.py
  test_data/test_expected_data.csv
  test_data/test_input_data.csv
Labels: enhancement

#17 Create codeql.yml
  .github/workflows/codeql.yml
Labels: enhancement

#16 Fix filtering
  .gitignore
  filter_data.py
  main.py
Labels: bug, enhancement

#19 Add pipfile
  Pipfile
  Pipfile.lock
Labels: enhancement

#18 Add cron job YAML
  .github/workflows/pull_data.yml
Labels: enhancement

#21 Update pull_data.yml
  .github/workflows/pull_data.yml
Labels: bug

#23 Create dependabot.yml
  .github/dependabot.yml
Labels: enhancement

#22 Create dependency-review.yml
  .github/workflows/dependency-review.yml
Labels: enhancement

#25 Edit git component of action
  .github/workflows/pull_data.yml
Labels: enhancement

#31 Add GitHub Actions cron workflow to allowed source identities.
  .chainguard/source.yaml
Labels: enhancement

#32 Add alert for failed pull_data job
  .github/workflows/pull_data.yml
Labels: enhancement
